capadjango_com/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
)

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<poll_id>\d+)/result/$', views.result, name='id_result'),
    url(r'^results/$', views.result, name='results'),
    url(r'^more_voted/$', views.more_voted, name='more_voted'),
    url(r'^vote_average/$', views.vote_average, name='vote_average'),
    url(r'^new_poll/$', views.poll_manage, name='new_poll'),
    url(r'^edit_poll/(?P<poll_id>\d+)/$', views.poll_manage, name='edit_poll'),
    url(r'^error/$', views.error, name='error'),
    #Logueo y Deslogueo
    url(r'^logueo/$', 'django.contrib.auth.views.login', {'template_name': 'polls/logueo.html'}, name='logueo'),
    url(r'^deslogueo/$', 'django.contrib.auth.views.logout', {'next_page': '/polls'}, name='deslogueo'),
)

polls/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.db.models import Sum, Avg
from django.contrib.auth.models import User


class Perfil(models.Model):
    direccion = models.CharField(max_length=150, null=True)
    telefono = models.CharField(max_length=150, null=True)
    user = models.OneToOneField(User, unique=True, related_name='perfil')

    def __unicode__(self):
        return self.user.username


class PollManager(models.Manager):
    def more_voted(self):
        polls = self.annotate(votes_count=Sum('choice__votes'))
        if polls:
            poll_more_voted = max(polls, key=lambda p: p.votes_count)
            more_voted = {'poll': poll_more_voted, 'total': poll_more_voted.votes_count}
            return more_voted
        else:
            return {}

    def vote_average(self):
        polls = self.annotate(votes_count=Sum('choice__votes'))
        if polls:
            vote_average = polls.aggregate(Avg('votes_count'))
            return vote_average['votes_count__avg']
        else:
            return 0


class Poll(models.Model):
    objects = PollManager()

    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.question

    class Meta:
        permissions = (
            ("puede_votar", "Puede Votar"),
        )

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def total_votes(self):
        if self.choice_set.all().count() > 0:
            total_votes = self.choice_set.aggregate(total=Sum('votes'))
            return total_votes['total']
        return 0


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        order_with_respect_to = 'poll'

    def __unicode__(self):
        return self.choice

    def percent_voted(self):
        total_votes = self.poll.total_votes()
        if total_votes > 0:
            return self.votes * 100 / total_votes
        return 0

polls/forms.py
from django import forms
from django.forms.models import BaseInlineFormSet
from polls.models import Choice, Poll


class VoteForm(forms.Form):
    choice = forms.ModelChoiceField(
        queryset=Choice.objects.all(),
        widget=forms.RadioSelect,
        empty_label=None,
    )

    def __init__(self, *args, **kwargs):
        poll = kwargs.pop('poll')
        super(VoteForm, self).__init__(*args, **kwargs)
        self.fields['choice'].queryset = poll.choice_set.all()


class PollForm(forms.ModelForm):
    class Meta():
        model = Poll
        fields = (
            'question',
            )


class BaseFormSet(BaseInlineFormSet):
    def add_fields(self, form, index):
        super(BaseFormSet, self).add_fields(form, index)
        form.fields['ORDER'].widget = forms.HiddenInput()

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.forms.models import inlineformset_factory
from django.views.generic import ListView, FormView, TemplateView
from django.utils.decorators import method_decorator

from polls.models import Poll, Choice
from polls.forms import VoteForm, PollForm, BaseFormSet


class LatestPolls(ListView):
    queryset = Poll.objects.order_by('-pub_date')[:5]
    context_object_name = 'latest_poll_list'
    template_name = 'polls/index.html'
index = LatestPolls.as_view()


class ResultPolls(ListView):
    def get_queryset(self, **kwargs):
        if 'poll_id' in self.kwargs:
            return get_list_or_404(Poll, pk=self.kwargs['poll_id'])
        else:
            return Poll.objects.all()
    context_object_name = 'polls'
    template_name = 'polls/results.html'
result = ResultPolls.as_view()


class MoreVotedPolls(TemplateView):
    model = Poll
    context_object_name = 'more_voted'
    template_name = 'polls/more_voted.html'

    def dispatch(self, request, *args, **kwargs):
        self.more_voted = Poll.objects.more_voted()
        return super(MoreVotedPolls, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MoreVotedPolls, self).get_context_data(**kwargs)
        context['more_voted'] = self.more_voted
        return context
more_voted = MoreVotedPolls.as_view()


class VoteAveragePolls(TemplateView):
    model = Poll
    context_object_name = 'vote_average'
    template_name = 'polls/vote_average.html'

    def dispatch(self, request, *args, **kwargs):
        self.vote_average = Poll.objects.vote_average()
        return super(VoteAveragePolls, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(VoteAveragePolls, self).get_context_data(**kwargs)
        context['vote_average'] = self.vote_average
        return context
vote_average = VoteAveragePolls.as_view()


class PollVote(FormView):
    form_class = VoteForm
    template_name = 'polls/vote.html'

    @method_decorator(login_required)
    @method_decorator(permission_required('polls.puede_votar', login_url='/polls/error'))
    def dispatch(self, request, *args, **kwargs):
        self.poll = get_object_or_404(Poll, pk=kwargs['poll_id'])
        return super(PollVote, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(PollVote, self).get_form_kwargs()
        kwargs.update({'poll': self.poll})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(PollVote, self).get_context_data(**kwargs)
        context['poll'] = self.poll
        return context

    def form_valid(self, form):
        choice = form.cleaned_data['choice']
        choice.votes += 1
        choice.save()
        return redirect('polls:id_result', poll_id=self.poll.id)
vote = PollVote.as_view()


@login_required
@permission_required('polls.add_poll', login_url='/polls/error')
@permission_required('polls.add_choice', login_url='/polls/error')
def poll_manage(request, poll_id=None):
    ChoiceFormSet = inlineformset_factory(Poll, Choice, exclude=('votes',), formset=BaseFormSet, can_order=True, can_delete=False, extra=2)
    poll = None
    if(poll_id):
        poll = get_object_or_404(Poll, pk=poll_id)
        ChoiceFormSet = inlineformset_factory(Poll, Choice, exclude=('votes',), formset=BaseFormSet, can_order=True, can_delete=True, extra=0)

    if request.method == 'POST':
        if 'guarda_poll' in request.POST:
            form_poll = PollForm(request.POST, instance=poll)
            if form_poll.is_valid():
                poll = form_poll.save()

                formset_choice_poll = ChoiceFormSet(request.POST, instance=poll)
                if formset_choice_poll.has_changed():
                    formset_choice_poll.save()

                    list_order = []
                    for form in formset_choice_poll.ordered_forms:
                        if(form.cleaned_data['id']):
                            list_order.append(form.cleaned_data['id'].id)
                    poll.set_choice_order(list_order)

                return redirect('polls:index')
            else:
                formset_choice_poll = ChoiceFormSet(request.POST, instance=poll)
    else:
        form_poll = PollForm(instance=poll)
        formset_choice_poll = ChoiceFormSet(instance=poll)

    context = {
        'form': form_poll,
        'formset_choice_poll': formset_choice_poll,
    }
    return render(request, 'polls/poll.html', context)


class Error(TemplateView):
    template_name = 'polls/error.html'
error = Error.as_view()

polls/templates/polls/base.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}

{% load url from future %}


<html>
<head>
    {% bootstrap_stylesheet_tag %}
    <title>Lo último en encuestas!</title>
    <link rel="stylesheet" href="/static/css/style.css" />
    
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.pack.js"></script>
    <script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
    {% block extra_head %}

    {% endblock %}
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <a class="brand" href="#">POLLS</a>

            <p class="navbar-text pull-right">
                {% if user.is_authenticated %} 
                    Hola! {% if user.get_full_name %} {{ user.get_full_name }} {% else %} {{ user.username }} {% endif %} | <a href="{% url 'polls:deslogueo' %}">Cerrar Sesión</a>
                {% else %}
                    <a href="{% url 'polls:logueo' %}">Iniciar Sesión</a>
                {% endif %}
            </p>
            <ul class="nav">
                <li class="dropdown"><a href="{% url 'polls:index' %}" class="dropdown-toggle" data-toggle="dropdown">Encuestas</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'polls:index' %}" >Lista Encuesta</a></li>  
                        {% if perms.polls.add_poll and perms.polls.add_choice %}
                            <li><a href="{% url 'polls:new_poll' %}" >Nueva Encuesta</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li><a href="{% url 'polls:results' %}">Resultados</a></li>
                <li><a href="{% url 'polls:more_voted' %}">Mas Votada</a></li>
                <li><a href="{% url 'polls:vote_average' %}">Promedio</a></li>
            </ul>
            
        </div>
    </div>
    {% if not user.is_authenticated %}
        <div class="alert">
            Debe estar logueado para poder votar.
        </div>
    {% endif %}
    <div class="hero-unit">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

polls/templates/polls/error.html
{% extends "polls/base.html" %}
{% load bootstrap_toolkit %}
{% load url from future %}

{% block content %}   
<div>
    <h4>No tiene permiso para realizar esta acción.</h4>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load url from future %}

{% block content %}
    <h4>Encuestas</h4>
    {% if latest_poll_list %}
        <ul  class="nav nav-list">
        <div class="row">
        {% for poll in latest_poll_list %}             
            <li>
                <div class="span6">
                    <h5>
                        {{ poll.question }}
                        {% if perms.polls.puede_votar %}
                            <a href="{% url 'polls:vote' poll_id=poll.id %}"> Votar </a>
                        {% endif %}
                        {% if perms.polls.add_poll and perms.polls.add_choice %}
                            <a href="{% url 'polls:edit_poll' poll_id=poll.id %}">| Editar</a>
                        {% endif %}
                    </h5>
                </div>
                <div class="span6"><h5>{{ poll.pub_date }}</h5></div>
            </li>
        {% endfor %}
        </div>
        </ul>
    {% else %}
        <p>No hay encuestas.</p>
    {% endif %}

{% endblock %}

polls/templates/polls/logueo.html
{% extends "polls/base.html" %}
{% load staticfiles %}
{% load bootstrap_toolkit %}
{% load url from future %}

{% block content %}   
<div id="pagina">
    <div id="logueo">
        <div  id="banda_superior"> 
                <h3>Acceso</h3>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <table id="tabla_inicio" summary="Acceso Sepri">                
                <tr id="fila_uno_inicio">
                    <td class="texto">Usuario</td>
                    <td class="caja-input">
                            {{ form.username }}
                    </td>
                </tr>
                <tr id="fila_dos_inicio">
                    <td class="texto">Contrase&ntilde;a</td>
                    <td class="caja-input">
                        {{ form.password }}
                    </td>
                </tr>
                <tr id="advise">
                
                <td id="advise_line" >
                    {% if form.errors %}
                        Los datos ingreados no son válidos.
                    {% endif %} 
                </td>   
                </tr>
                <tr>
                    <td></td>
                    <td id="bt-entrar">
                        <input  type="submit" name="login" id="login"  value="Entrar" />
                        <input type="hidden" name="next" value="{{ next }}" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
{% endblock %}

polls/templates/polls/more_voted.html
{% extends "polls/base.html" %}
{% load url from future %}

{% block content %}
    <h4>Mas Votada</h4>
    {% if more_voted %}
        <ul  class="nav nav-list">
            <li><h5>{{ more_voted.poll.question }}: <span class="badge badge-success">{{ more_voted.total }} Votos</span></h5></li>
        </ul>
    {% else %}
        <p>No hay votos.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/poll.html
{% extends "polls/base.html" %}
{% load staticfiles %}
{% load bootstrap_toolkit %}
{% load url from future %}
    
{% block extra_head %}
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
    <script type="text/javascript" src="{% static 'js/script_choices.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock %}

{% block content %}   
    <h4>{{ poll.question }}</h4>
    <form id="myForm" action="" method="post">
        {% csrf_token %}
            <h5>Pregunta Encuesta</h5>   
            {{ form.question.errors }} 
            {{ form.question }}
            <h5>Opciones</h5>      
            {{ formset_choice_poll.management_form }}
            <ul id="sortable">
                {% for form in formset_choice_poll %}
                    <li class="li_sortable">
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}                        
                    </li>
                {% endfor %}
             </ul>      
        <button name="guarda_poll" type="submit">Guardar</button>
    </form>
    <script type="text/javascript">
        $('#myForm ul li').formset({
            prefix: '{{ formset_choice_poll.prefix }}'
        });
        $('.li_sortable').append('<img width="50px" height="50px" src="{% static "img/move.png" %}">');
    </script>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load poll_tags %}

{% block content %}
    <h4>Resultado</h4>
    {% if polls %}
        {% for poll in polls %}
            <ul  class="nav nav-list">
                <h5><strong>{{ poll.question }}</strong>
                {% if perms.poll.puede_votar %}
                    <a href="{% url 'polls:vote' poll_id=poll.id %}"> Votar</a></h5>
                {% endif %}
                {% for choice in poll.choice_set.all %}
                    <li><h6>{{ choice.choice }}: <span class="badge badge-info">{{ choice.votes }} </span>{% progress_bar choice %}</h6>
                   </li>
                {% endfor %}
            </ul>
            <br>
        {% endfor %}
    {% else %}
        <p>No hay encuestas.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/vote.html
{% extends "polls/base.html" %}
{% load bootstrap_toolkit %}
{% load url from future %}

{% block content %}
    <h4>{{ poll.question }}</h4>

    <form action="{% url 'polls:vote' poll_id=poll.id %}" method="post">
        {% csrf_token %}

        {{ form.choice }}
        
        <button type="submit">Votar</button>
    </form>
{% endblock %}

polls/templates/polls/vote_average.html
{% extends "polls/base.html" %}
{% load url from future %}

{% block content %}
    <h4>Promedio de Votos por Encuesta.</h4>
    <ul  class="nav nav-list">
        <li><h4><span class="badge badge-success">{{ vote_average }} Votos</span></h4></li>
    </ul>
{% endblock %}